Update bestreams.py
bestreams.py is currently broken due to changes on the site.
This update is to get us all on the same track, towards finding an answer to get it working again later.

File-url:  would be prefered to use but currently has like 38/9056497522_n.mp4?h= and then lowercase letters and numbers of around 60 digits i think.

Stream-url:  would be a decent fallback measure or temp. fix if it would work.  I get the following error. I've even tried with adding a few usual rtmp variables onto the end of the url, but no luck yet.  Someone might give this some further looking to see if they can get it going again.
ERROR: RTMP_ReadPacket, failed to read RTMP packet header